### ISSUE TITLE
Case issue when using snake case for model names

### ISSUE THREAD

**Issue by chrisbull** [Cauen/prisma-generator-pothos-codegen#11]
First I want to say thank you for creating this. This is dope and very helpful!

However I have noticed an issue with this plugin when using snake case names for models. I'm using this to build out an API for an existing database, and I have database with about 50 tables. All the names are snake case in the mysql database. So when generating the prisma schema, all the tables are snake case such as `activity_feed`. But when the generator runs, it's upper case in the `inputs.ts` file, but is lowercase in the generated files that point to it. So I immediately get errors because the variable is not matching. 

For example `model activity_feed` generates a variable in the `inputs.ts` file named `Activity_feedScalarFieldEnum` but then in the `findMany.base.ts` file, code is generated that looks like ` distinct: t.arg({ type: [Inputs.activity_feedScalarFieldEnum], required: false }),` ... so the `Inputs.activity_feedScalarFieldEnum` does not match because the `A` is not `a`

Can you please fix? Thank you!

**Comment by Cauen** [comment]
Hi @chrisbull 
Thanks for using this and reporting errors
I tested and fixed the errors
I published a new version 0.4.5

Can you please check if everything worked now?
