### ISSUE TITLE
Yarn or PNPM

### ISSUE THREAD

**Issue by saphewilliam** [Cauen/prisma-generator-pothos-codegen#31]
Is this repo using yarn or pnpm as a package manager? There is both a yarn.lock file and a pnpm-lock.yml file in the master branch at the moment.

**Comment by Cauen** [comment]
Started using pnpm, once its better
I'll delete yarn.lock file

**Comment by Cauen** [comment]
Since I mistakenly uploaded the file, I will delete it for now
We'll use it again when I can guarantee it works like yarn already works in the project
