### ISSUE TITLE
Change the generated queries and mutations

### ISSUE THREAD

**Issue by jw** [Cauen/prisma-generator-pothos-codegen#35]
This is a great tool!  Thanks a lot!

Is it possible to rename the generated queries/mutations (like `findFirstFoo`), into something else (like foo)?
Or is there a way to change the queries/mutations after generation?  Could anybody give an example?

**Comment by elritz** [comment]
Not exactly sure what you are looking for in terms of format but here is an example:
You get the QueryObject and use the properties on the field prop to complete the query
```
builder.queryFields((t) => {
  const field = findFirstProfileQueryObject(t);
  return {
    **ChangeTheName**: t.prismaField({
      ...field,
      type: Profile,
      args: {
        ...field.args,
      },
      shield: allow,
      resolve: async (query, root, args, context, info) => {
        const profile = await prismaClient.profile.findFirstOrThrow({
          ...query,
          where: {
            id: {
              equals: args.where.id.equals,
            },
          },
        });
         return {
          ...profile,
        };
      },
    }),
  };
});
```

**Comment by Cauen** [comment]
@jw 
We dont generate queries/mutations by default
By optionally running `autocrud`, it generates everything automatically...
But if you want, you can exclude some models from generation and define them with custom names like elritz example

Optionally, you can use `replace` function to change everything in generated code.

**Comment by jw** [comment]
Thanks!
