### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'scalarType')

### ISSUE THREAD

**Issue by taylorbindon** [Cauen/prisma-generator-pothos-codegen#64]
Hi all! Appreciate the great work on the package so far.

I'm working with a team that are migrating from nexus to pothos. We've used auto generated crud in the past and would like to going forward for this project.

We've run into a strange issue. It looks like the inputs file is not getting the builder correctly. The path is correct but we keep getting this error: **TypeError: Cannot read properties of undefined (reading 'scalarType')**. This happens specifically at the first scalar in the input file (DateTime). See screenshot attached at line 37 builder.scalarType.

![image](https://github.com/Cauen/prisma-generator-pothos-codegen/assets/38872488/a6570a1c-5c28-4b87-afb9-f9ed5249b7fb)

I'm running:
Node: 20.10
@pothos/core: ^3.41.0
@pothos/plugin-prisma: ^3.63.1
@prisma/client: ^5.7.1
prisma: ^5.7.1

It's strange because the generated files are picking up the inputs file and the builder, but specifically the inputs file is not picking up the builder. Worth noting the path is correct and is exporting correctly as all the generated files get the builder fine as I said.

Any help would be great!

**Comment by Cauen** [comment]
Hello @taylorbindon
Can you please setup a small example with that error?
The example in repo does work for you?

**Comment by taylorbindon** [comment]
I've tried to follow the example as best as I can, everything seems to be fine except this.

Code sandbox below is a very minimal reproduction but this time it's enumType instead of Scalar. The Prisma scalar definitions aren't coming through from the package on code sandbox for some reason.

[Code sandbox example](https://codesandbox.io/p/devbox/node-js-k8dsq1?file=%2Fpackage.json&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr7qybjo0006356ijzfof0pd%2522%252C%2522sizes%2522%253A%255B74.91428571428571%252C25.08571428571429%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr7qybjo0002356iqbry56px%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr7qybjo0004356ifbgkxj9e%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr7qybjo0005356iegtuehos%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr7qybjo0002356iqbry56px%2522%253A%257B%2522id%2522%253A%2522clr7qybjo0002356iqbry56px%2522%252C%2522activeTabId%2522%253A%2522clr7s3zxh0272356ir60kkrod%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr7qybjo0001356i71zipd6s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fgenerated%252Finputs%252Findex.ts%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A39%252C%2522endLineNumber%2522%253A39%252C%2522startColumn%2522%253A50%252C%2522endColumn%2522%253A50%257D%255D%252C%2522id%2522%253A%2522clr7s3zxh0272356ir60kkrod%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clr7qybjo0005356iegtuehos%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clr7qybjo0005356iegtuehos%2522%257D%252C%2522clr7qybjo0004356ifbgkxj9e%2522%253A%257B%2522id%2522%253A%2522clr7qybjo0004356ifbgkxj9e%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr7qybjo0003356i9vzvrl9k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clr7r8s8o00zp356i5htzmdq6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr7r8sdb031yeeg60blz1hrq%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr7r8s8o00zp356i5htzmdq6%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by Cauen** [comment]
Have you setup builderLocation?
![image](https://github.com/Cauen/prisma-generator-pothos-codegen/assets/8796757/3a531643-9afc-49f6-bc91-d0ae0acd30b0)

**Comment by taylorbindon** [comment]
Yeah tried that as well, locally I still get scalarType error, code sand box still gets enumType error. Have you run into this before?

**Comment by Cauen** [comment]
Its a problem with circular dependency
Please break builder into an isolated file

See the fix

https://github.com/Cauen/pgpc-issue-64/commit/c1607faacbdc2c8c6cdac40263e2e7c7073b325b

Does it resolve your issue?

**Comment by taylorbindon** [comment]
Legend, makes sense! Sure enough it's fixed now.

Appreciate the help!
