### ISSUE TITLE
please update the peer dependencies for "@pothos/core" and "@pothos/plugin-prisma" to version >= 4.1

### ISSUE THREAD

**Issue by ad6025b** [Cauen/prisma-generator-pothos-codegen#73]
@Cauen  please update the pothos peer dependencies in https://github.com/Cauen/prisma-generator-pothos-codegen/blob/master/package.json

    "@pothos/core": "^3.23.0",
    "@pothos/plugin-prisma": "^3.37.0",
    

 **please update them  to latest >4.1 versions**    
    "@pothos/core": "^4.1.0",
    "@pothos/plugin-prisma": "^4.2.1",
    
the context is that  pothos recently updated their package to 4.x to fix https://github.com/prisma/prisma/issues/23913
     -> prisma dmmf issue   (see last comment on ticket)

**Comment by ad6025b** [comment]
@Cauen  btw, i see your version 0.7.0 has the 4.0 
-> https://github.com/Cauen/prisma-generator-pothos-codegen/commit/25f71f5bb7e933275a63287b07d2e9e126ba5420

but it still failed, and i had to force the @pothos/core@4.1.0 to be installed  

npm install @pothos/core@4.1.0 --legacy-peer-deps

**Comment by Cauen** [comment]
Thanks for you contribution @ad6025b, thanks to @mmm888 its now fixed
Sorry for the delay, had no much time for that :x
