### ISSUE TITLE
is there a way to add custom property to all resolvers?

### ISSUE THREAD

**Issue by ad6025b** [Cauen/prisma-generator-pothos-codegen#79]
i want to add :
`authScope: {admin: true} `

to all queries and mutations.

is there a easy way to do this, without have to iterate through every query/mutation object?

![image](https://github.com/user-attachments/assets/6031ad7f-4afc-42ef-8940-6e849276edff)

**Comment by Cauen** [comment]
Hello @ad6025b 
I think that file has the answers you're searching for https://github.com/Cauen/prisma-generator-pothos-codegen/blob/master/examples/inputs-simple-sqlite/src/schema/index-3-global-crud-handle-resolvers.ts 
It shows how to customize globally the crud from "autocrud"

**Comment by ad6025b** [comment]
@Cauen  thank you so much!  this is perfect.
