### ISSUE TITLE
Generator bin is `CRLF` 

### ISSUE THREAD

**Issue by snake575** [Cauen/prisma-generator-pothos-codegen#9]
The `CRLF` line ending causes this error with the generator on unix:

```bash
env: node\r: No such file or directory
```
<img width="556" alt="image" src="https://user-images.githubusercontent.com/4157289/191400189-df817137-0efc-4682-90bf-f8f2d23172ef.png">

**Comment by Diederik98** [comment]
I solved this issue on macOS by adding the following line in `scripts` in my `package.json`:  `"install": "find node_modules/prisma-generator-pothos-codegen -name \"*.js\" | xargs dos2unix"`. dos2unix is a program I installed using homebrew

**Comment by snake575** [comment]
Thanks, solved it using a similar solution. The file should be saved as `LF` before uploading to npm though 🤔

**Comment by Cauen** [comment]
@snake575  @Diederik98 Thanks for your contribution
Published new version 0.4.3 with `LF`
Now `tsconfig.json` are configured to build using `LF`
